app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))






class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    posts = db.relationship('Post', backref='user', lazy='dynamic')
    comments = db.relationship('Comments', backref='user', lazy='dynamic')
    subscribe = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')


    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

    @classmethod
    def check_role(cls,user_id,role_id):
        get_role = User.query.filter_by(id=user_id).filter_by(role_id=role_id).first()
        return get_role

    def save_user(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def subcribe_user(cls,user_id):
        user = User.query.filter_by(id=user_id).update({
            'subscribe':True
            })
        db.session.commit()

    @classmethod
    def get_subscribers(cls):
        users = User.query.filter_by(subscribe=True).all()
        users_emails = []
        for user in users:
            users_emails.append(user.email)
        return users_emails


class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __repr__(self):
        return f'User {self.name}'


class Post(db.Model):

    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key = True)
    post_title = db.Column(db.String)
    post_content = db.Column(db.String)
    post_date = db.Column(db.DateTime, default=datetime.now())
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comments', backref='post', lazy='dynamic', cascade="all, delete-orphan")

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_posts(cls):
        posts = Post.query.order_by(Post.id.desc()).all()
        return posts

    @classmethod
    def delete_post(cls,post_id):
        comments = Comment.query.filter_by(post_id=post_id).delete()
        post = Post.query.filter_by(id=post_id).delete()
        db.session.commit()



class Comments(db.Model):
    __tablename__ = 'comments'

    # table columns
    id = db.Column(db. Integer,primary_key = True)
    comment_content = db.Column(db.String)
    date_posted = db.Column(db.DateTime,default=datetime.now)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    post_id = db.Column(db.Integer, db.ForeignKey("posts.id",ondelete='CASCADE') )

    def save_comments(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(self,id):
        comment = Comments.query.order_by(Comments.date_posted.desc()).filter_by(post_id=id).all()
        return comment

    @classmethod
    def delete_single_comment(cls,comment_id):
        comment = Comments.query.filter_by(id=comment_id).delete()
        db.session.commit()
 

    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class CommentForm(FlaskForm):

    
    comment_content = TextAreaField('Insert Comment here', validators = [Required()])
    submit = SubmitField('Submit')


class PostForm(FlaskForm):
	post_title = StringField('Post Title')
	post_content = TextAreaField('Insert thoughts here', validators = [Required()])
	submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE



login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'




bootstrap = Bootstrap()

db = SQLAlchemy()

photos = UploadSet('photos',IMAGES)

mail = Mail()

simple = SimpleMDE()



def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations

    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)

    # Initializing flask extensions
    bootstrap.init_app(app)

    db.init_app(app)

    login_manager.init_app(app)

    mail.init_app(app)
    
    simple.init_app(app)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)


    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    

    # configure UploadSet
    configure_uploads(app,photos)


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import CommentForm,UpdateProfile,PostForm
from ..models import User, Post,Comments, Role
from flask_login import login_required, current_user
from .. import db,photos
import markdown2




@main.route('/')
def index():
    
    posts = Post.get_posts()
    title = 'Phil Blog'
    return render_template('index.html', title = title, posts = posts )




@main.route('/post/<int:id>')
def post(id):

    post = Post.query.get(id)

    if post is None:
        abort(404)
        
    comments = Comments.get_comments(id)
    title = "Posts"
    return render_template('post.html', title=title, post=post, comments=comments )



@main.route('/post/comment/new/<int:id>', methods=['GET','POST'])
@login_required
def new_comment(id):

    form = CommentForm()
    post = Post.query.filter_by(id=id).first()

    if post is None:
        abort(404)

    

    if form.validate_on_submit():
        comment_content = form.comment_content.data
        new_comment = Comments( comment_content=comment_content, post=post, user=current_user)
        new_comment.save_comments()

        return redirect(url_for('.post', id=post.id ))

    title = 'New Comment'
    return render_template('new_comment.html', title=title, comment_form=form)





@main.route('/post/comment/delete/<int:id>')
@login_required
def delete_comment(id):

        comment = Comments.query.get(id)
        comment.delete_single_comment(id)

        return redirect(url_for('.index'))





@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)





@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)




@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}



{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}


<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/fourOwfour.html
<link href="https://fonts.googleapis.com/css?family=Tangerine&display=swap" rel="stylesheet">  
{% extends 'base.html'%}

{% block content %}
<div class="container-fluid">

	  <style>
      h1 {
        font-family: 'Tangerine', cursive;
        font-size: 78px;
        text-shadow: 4px 4px 4px #aaa;
        text-align: center;
        margin-top: 35px;
      }
    </style>
    <h1>Nothing here</h1>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

<!-- Styles block -->

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}


<!-- Content block -->
{% block content %}



<div class="container">

	 
	<div class="row">
		

		
		<h2>Blogs Posted</h2>

		</div>

		<hr>


	<div class="row">
		

		 <ul class="list-unstyled" style="font-size: 15px;">
            {{ macro.displayPosts(posts)}}
        </ul>


	</div>

	
</div>
{% endblock%}

app/templates/macros.html
{% macro displayPosts(posts_list) %} 
  {% for posts in posts_list%}



<style>

  .text-right {
  font-size: 34px;
  }
  #time {
    font-size: 25px;
  }


</style>




    <div class="well well-lg col-xs-12 col-sm-12 col-md-12 col-lg-12 pitch-card text-center">
      <h3> <a href="/post/{{posts.id}}"> {{ posts.post_title }} </a></h3>
      <p> {{ posts.post_content | truncate(45) }} </p>

    </div> 
    {% endfor%}
{% endmacro%}






<!-- Display Comments -->
{% macro displayComments(comment_list) %} 
{% for comment in comment_list%}




 <style>
      
      .list-group {
        font-size: 19px;

      }

     

    </style>
  <ul class="list-group">
  <li class="list-group-item list-group-item-info">
    {{ comment.comment_content}}
    <br><br>
    <p class="text-right">Posted by {{ comment.user.username }} on:{{comment.date_posted.strftime('%B %d, %Y %r')}}</p>
    <a class="btn btn-success btn-lg text-center" href="/post/comment/delete/{{comment.id}}">Delete Comment</a>
                
                
            
  </li>
  </ul>
{% endfor%}
{% endmacro%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="font-size: 35px; color: yellow" href="/"> Phil Blog </a>
            </div>
            <div class="navbar-collapse collapse">
                
    
                 <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                  <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                  <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                  {% else %}
                  <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                  {%endif%}
                </ul>

            </div>

        </div>
    </div>

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}


<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

<!-- Content block -->
{% block content %}
    <title> {{ title }} </title>
    
    <div class="container">

        <div class="row">
            
            <div class="col-md-2 col-lg-2">
                
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-comment">
            
                {{ wtf.quick_form(comment_form) }}
                
            </div>

            <div class="col-md-2 col-lg-2">
                
            </div>

        </div>
    </div>
{% endblock %}

app/templates/new_post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}


<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

<!-- Content block -->
{% block content %}
    <title> {{ title }} </title>
    
    <div class="container">

        <div class="row">
            
            <div class="col-md-2 col-lg-2">
                
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-post">
            
                {{ wtf.quick_form(post_form) }}
                
            </div>

            <div class="col-md-2 col-lg-2">
                
            </div>

        </div>
    </div>
{% endblock %}

app/templates/post.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}


<!-- Content block -->
{% block content %}

    <title> {{ title }} </title>

    <div class="container">

        <div class="row">

            <div class="col-sm-2 col-md-2 col-lg-2">

                <a href="/">

                    <i class="glyphicon glyphicon-menu-left back-icon"></i>

                </a>
            
            </div>

            <div class="col-sm-10 col-md-10 col-lg-10">

                <h2 class="post-title"> 
                    {{ post.post_title }}
                    <br>
                    <small class="writer">
                        by {{ post.user.username }}
                    </small> 
                </h2>

                <p> {{ post.post_content }} </p>
                
            </div>

        </div>

        <hr>

        <div class="row">

            <div class="col-xs-6 col-sm-4 col-md-4 col-lg-4">

                <h3 class="comment-header">Comments</h3>

            </div>

            <div class="col-sm-4 col-md-4 col-lg-4">
                
            </div>

            <div class="col-xs-6 col-sm-4 col-md-4 col-lg-">
                
                <h3 class="comment-create">
                    <a href="/post/comment/new/{{post.id}}">
                        Add Comment
                    </a>
                </h3>
            </div>
        </div>

        <hr>
        
        <ul class="list-unstyled">
            {{ macro.displayComments(comments) }}
        </ul>



    </div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>

    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}


    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>

</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}